# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-27 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0022_auto_20170327_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('distance', models.CharField(max_length=60)),
                ('duration', models.CharField(max_length=60)),
                ('max_speed', models.CharField(max_length=60)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('in_ride_now', models.BooleanField(default=False)),
                ('path_file', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('start_place', models.CharField(max_length=120, null=True)),
                ('end_place', models.CharField(max_length=120, null=True)),
                ('bicycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Bicycle')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Motorcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
