# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-27 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='max_speed',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
