# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleridemembership',
            old_name='group',
            new_name='schedule_ride',
        ),
        migrations.RenameField(
            model_name='scheduleridemembership',
            old_name='person',
            new_name='user',
        ),
    ]
