# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_ride', '0002_auto_20170402_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRideJoiningRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('p', 'Pending'), ('I', 'Ignored'), ('A', 'Accepted')], max_length=1, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('schedule_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_ride.ScheduleRide')),
            ],
        ),
    ]
