# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ride', '0003_scheduleridejoiningrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleridejoiningrequests',
            name='schedule_ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_ride.ScheduleRide'),
        ),
    ]
