# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ride', '0004_auto_20170402_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleridejoiningrequests',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleridejoiningrequests',
            name='schedule_ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule_ride.ScheduleRide'),
            preserve_default=False,
        ),
    ]
