# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0022_auto_20170327_1336'),
        ('schedule_ride', '0006_scheduleridejoiningrequests_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleride',
            name='bicycle',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='motorcycle',
        ),
        migrations.AddField(
            model_name='scheduleridemembership',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Bicycle'),
        ),
        migrations.AddField(
            model_name='scheduleridemembership',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Motorcycle'),
        ),
        migrations.AlterField(
            model_name='scheduleridejoiningrequests',
            name='request_status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Denied'), ('A', 'Approved'), ('C', 'Cancelled')], max_length=1, null=True),
        ),
    ]
