# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0022_auto_20170327_1336'),
        ('schedule_ride', '0007_auto_20170406_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleridejoiningrequests',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Bicycle'),
        ),
        migrations.AddField(
            model_name='scheduleridejoiningrequests',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Motorcycle'),
        ),
    ]
