# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='aaa', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
