# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20160729_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
    ]
