# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_customuser_is_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fb_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
