# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_auto_20160807_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'avatar/%Y/%m/%d', verbose_name=b'profile picture'),
        ),
    ]
