# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_auto_20160819_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'avatar/%Y/%m', verbose_name=b'profile picture'),
        ),
    ]
