# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0014_contact_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
