# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0015_subscriber_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='message date'),
        ),
    ]
