# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0017_auto_20161002_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
