# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0020_auto_20170103_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(default='1234', max_length=4),
            preserve_default=False,
        ),
    ]
