# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0027_auto_20170225_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Settings'),
        ),
    ]
