# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0028_auto_20170225_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='setting',
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
