# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0032_auto_20170310_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ride',
        ),
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
