# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0033_auto_20170310_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
                ('is_break', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='lang',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='lat',
            new_name='started_from',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='is_break',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.CharField(default=55, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.CharField(default=4, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='max_speed',
            field=models.CharField(default=70, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Ride'),
        ),
    ]
