# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0034_auto_20170310_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='time',
            field=models.IntegerField(max_length=120),
        ),
    ]
