# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-11 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0035_auto_20170310_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='ended_at',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='started_from',
            new_name='lat',
        ),
    ]
