# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-11 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0036_auto_20170311_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='lang',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='lang',
            new_name='lng',
        ),
    ]
