# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0038_auto_20170312_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ridefile',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
