# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-18 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0039_customuser_ridefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
