# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0040_auto_20170318_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
