# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0041_subscriber_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
