# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20160823_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.BicycleMake'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.BicyceStyle'),
        ),
    ]
