# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_auto_20160826_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MotorMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MotorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.MotorMake')),
            ],
        ),
        migrations.CreateModel(
            name='MotorStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='year',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='production_year',
            field=models.CharField(default='1990', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.MotorEngine'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.MotorMake'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.MotorModel'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='style',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='garage.MotorStyle'),
            preserve_default=False,
        ),
    ]
