# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_auto_20160827_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorcycle',
            old_name='model',
            new_name='motor_model',
        ),
    ]
