# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_auto_20160921_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='color',
            field=models.CharField(default=45711, max_length=120),
            preserve_default=False,
        ),
    ]
