# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_bicycle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
