# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_motorcycle_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycestyle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bicyclemake',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
