# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_auto_20170224_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=120)),
            ],
        ),
    ]
