# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-18 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0014_bicyclenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_break', models.BooleanField(default=False)),
                ('time', models.IntegerField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('distance', models.CharField(max_length=60)),
                ('duration', models.CharField(max_length=60)),
                ('max_speed', models.CharField(max_length=60)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('bicycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Bicycle')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Motorcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Ride'),
        ),
    ]
