# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0015_auto_20170318_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='bicycles',
            field=models.ManyToManyField(blank=True, to='garage.Bicycle'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='motorcycles',
            field=models.ManyToManyField(blank=True, to='garage.Motorcycle'),
        ),
        migrations.AlterField(
            model_name='point',
            name='time',
            field=models.IntegerField(),
        ),
    ]
