# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0016_auto_20170323_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=120)),
                ('engine_size', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
            ],
        ),
    ]
