# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0018_auto_20170326_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='path_file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
