# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0019_auto_20170326_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='in_ride_now',
            field=models.BooleanField(default=False),
        ),
    ]
