# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0020_ride_in_ride_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='ride',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_place',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_place',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
