# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0022_auto_20170327_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmotorcycle',
            name='engine_size',
        ),
        migrations.RemoveField(
            model_name='newmotorcycle',
            name='style',
        ),
    ]
