# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0023_auto_20170409_1147'),
        ('schedule_ride', '0008_auto_20170406_1624'),
        ('ride', '0003_auto_20170327_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('action_bicycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Bicycle')),
                ('action_motorcycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Motorcycle')),
                ('action_myplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.MyPlaces')),
                ('action_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_ride.ScheduleRideJoiningRequests')),
                ('action_ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.Ride')),
                ('action_schedule_ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_ride.ScheduleRide')),
                ('feed_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
